server:
  port: 7001
eureka:
  instance:
    hostname: eureka9001.com #eureka服务端的实例名称
    instance-id: eureka9001
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false # #false 表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaulteZone: http://127.0.0.1:${server.port}