#spring:
#  application:
#    name: licensingservice
#  profiles:
#    active:
#      default
#  cloud:
#    config:
#      uri: http://localhost:8888
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh
#  security:
#    enabled: false
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:8002/auth/user
    client:
      client-id: client
      client-secret: $2a$10$r5vSTD7377q4m7AImGc2XehvfWcMyxcoJsQhjYvqx/eRzYzTqV9VO